.Dd 6/20/12               \" DATE 
.Dt jsonpp 1      \" Program name and manual section number 
.Os Darwin
.Sh NAME                 \" Section Header - required - don't modify 
.Nm jsonpp
.\" The following lines are read in generating the apropos(man -k) database. Use only key
.\" words here as the database is built based on the words here and in the .ND line. 
.\" Use .Nm macro to designate other names for the documented program.
.Nd Parse and pretty-print JSON data.
.Sh SYNOPSIS             \" Section Header - required - don't modify
.Nm
.Op Ar file              \" [file]
.Sh DESCRIPTION          \" Section Header - required - don't modify
.Pp
.Nm 
validates and pretty-prints json either from a file or standard input. If a file 
is specified as an argument, it is used as input, otherwise, standard input is assumed.
.Pp
.Pp
.Sh FILES                \" File used or created by the topic of the man page
.Bl -tag -width "/Users/joeuser/Library/really_long_file_name" -compact
.It Pa /usr/bin/jsonpp
.El                      \" Ends the list
.\" .Sh DIAGNOSTICS       \" May not be needed
.\" .Bl -diag
.\" .It Diagnostic Tag
.\" Diagnostic informtion here.
.\" .It Diagnostic Tag
.\" Diagnostic informtion here.
.\" .El
.\" .Sh BUGS              \" Document known, unremedied bugs 
.\" .Sh HISTORY           \" Document history if command behaves in a unique manner
.Sh AUTHOR
.Pp
P. Taylor Goetz (ptgoetz@gmail.com)